CURRENT_EPOCH: 0
TRAIN:
  DEBUG: False
  DATASET:
    NAME: JointsDataset
    CONTAINS:
      STB:
        ROOT: data/STB/2dcrop
        DATA_JSON_PATH: data/STB/labels
        PICK:
          - B2Counting
          - B3Counting
          - B4Counting
          - B5Counting
          - B6Counting
          - B2Random
          - B3Random
          - B4Random
          - B5Random
          - B6Random
    REPROCESS:
      TRANSFORMS:
        RESIZE: 256
        FLIP: False
        COLOR_NORISE: True
      HEATMAP:
        TYPE: Gaussian # Gaussian or Cauchy
        SIGMA: 8 #Ground truth heatmap
      NUM_JOINTS: 22
    IS_TRAIN: True
    BATCH_SIZE: 6
    SHUFFLE: True
    

VALID:
  DEBUG: False
  IS_VALID: True
  NUM_JOINTS: 21
  DATASET:
    NAME: JointsDataset
    CONTAINS:
      STB:
        ROOT: data/STB/2dcrop
        DATA_JSON_PATH: data/STB/labels
        PICK:
          - B1Counting
          - B1Random
    REPROCESS:
      TRANSFORMS:
        RESIZE: 256
        FLIP: False
        COLOR_NORISE: False
      HEATMAP:
        TYPE: Gaussian # Gaussian or Cauchy
        SIGMA: 8 #Ground truth heatmap
      NUM_JOINTS: 22
    IS_TRAIN: False
    BATCH_SIZE: 6
    
    
DATA_DIR: ''
END_EPOCH: 100

LOG_DIR: ''
MODEL:
  NAME: Weakly_direct_regression
  NETWORKS:
    Regression:
      TYPE: CPMWeaklyDirectRegression
      PRETRAINED_WEIGHT_PATH: pretrained_weight/cpmRHD.torch
      # PRETRAINED_WEIGHT_PATH: 'output/Mar  7 21:58:35_train_Weakly_direct_regression_Combine2D(RHD2D)_valid_Combine2D(RHD2D)/best/model/net_Regression.torch'
      # PRETRAINED_WEIGHT_PATH: 'Mar_13_04:52:55_direct_two_stream_train:RHD2D_valid:RHD2D/best/model/net_direct_two_stream.torch'
      num_joints: 22

  OPTIMIZERS:
    Regression:
      NETWORKS:
        - Regression
      TYPE: RMSprop
      PARAMETERS:
        lr: 2.5e-5
        momentum: 0
        weight_decay: 0
      SCHEDULER:
        TYPE: StepLR
        PARAMETERS:
          gamma: 0.1
          step_size: 30
  GPUS:
    - 0
    - 1
    - 2
    - 3
  STAGE: 3
LOG:
  PATH: output
  MONITOR_ITEM:

METRIC_ITEMS: # the metric that you wanna track during training
  - loss
  - dis2d
  - dis3d
  - AUC_20_50
MAIN_METRIC: dis3d

OUTPUT_DIR: output/
START_EPOCH: 0
WORKERS: 6
RESUME_TRAIN: 0
